"""add d/t to device log

Revision ID: 8fdbb27c846c
Revises: adff85240d0b
Create Date: 2025-01-23 11:09:01.066203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdbb27c846c'
down_revision = 'adff85240d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_log', schema=None) as batch_op:
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###
