"""add device log

Revision ID: adff85240d0b
Revises: dd141d20d2c6
Create Date: 2025-01-23 10:35:57.538248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adff85240d0b'
down_revision = 'dd141d20d2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('device', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_log')
    # ### end Alembic commands ###
